### ISSUE TITLE
Latest version is not in the repository

### ISSUE THREAD

**Issue by tprochazka** [patrikerdes/gradle-use-latest-versions-plugin#15]
According to the readme, the latest version is 0.2.7, but in the official Gradle plugin repository is just 0.2.3. 

https://plugins.gradle.org/m2/gradle/plugin/se/patrikerdes/gradle-use-latest-versions-plugin/

Btw. Thanks for great plugin!

**Comment by usr42** [comment]
The newer versions can be found here:
https://plugins.gradle.org/m2/se/patrikerdes/gradle-use-latest-versions-plugin/

How to use it in gradle see: https://plugins.gradle.org/plugin/se.patrikerdes.use-latest-versions

I use it with the plugin DSL and it's working for me:
```
plugins {
    id 'se.patrikerdes.use-latest-versions' version '0.2.7'
}
```

**Comment by patrikerdes** [comment]
I can confirm that the plugin format works, and that the buildscript one does not 

```
# .\gradlew.bat useLatestVersions
...
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'publishedReadmeExample'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find gradle.plugin.se.patrikerdes:gradle-use-latest-versions-plugin:0.2.7.
     Searched in the following locations:
         https://plugins.gradle.org/m2/gradle/plugin/se/patrikerdes/gradle-use-latest-versions-plugin/0.2.7/gradle-use-latest-versions-plugin-0.2.7.pom
         https://plugins.gradle.org/m2/gradle/plugin/se/patrikerdes/gradle-use-latest-versions-plugin/0.2.7/gradle-use-latest-versions-plugin-0.2.7.jar
         https://jcenter.bintray.com/gradle/plugin/se/patrikerdes/gradle-use-latest-versions-plugin/0.2.7/gradle-use-latest-versions-plugin-0.2.7.pom
         https://jcenter.bintray.com/gradle/plugin/se/patrikerdes/gradle-use-latest-versions-plugin/0.2.7/gradle-use-latest-versions-plugin-0.2.7.jar
     Required by:
         project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
```

I'm using the `com.gradle.plugin-publish` plugin version 0.10.0 to publish the plugin. I'm not sure why it uploads to the wrong place.

Help wanted.

**Comment by patrikerdes** [comment]
So, apparently things have changed at some point in time, the instructions for buildscript in the README are incorrect. When following the instructions on this page it works https://plugins.gradle.org/plugin/se.patrikerdes.use-latest-versions

I'll update the README.
