### ISSUE TITLE
Plugin uses hard coded build dir

### ISSUE THREAD

**Issue by eikemeier** [patrikerdes/gradle-use-latest-versions-plugin#24]
If `buildDir` is redefined (for example by setting `buildDir = file 'gradle-build'` in `build.gradle`), `useLatestVersions` fails with `java.nio.file.NoSuchFileException` while trying to open `dependencyUpdates/report.json`.

This is because [UseLatestVersionsCheckTask](/patrikerdes/gradle-use-latest-versions-plugin/blob/master/src/main/groovy/se/patrikerdes/UseLatestVersionsCheckTask.groovy#L19) looks for `new File(project.projectDir,  'build' + File.separator + 'dependencyUpdates' + File.separator + 'report.json')` while it should probably be something like `new File(project.buildDir, 'dependencyUpdates' + File.separator + 'report.json')`.

**Comment by patrikerdes** [comment]
Yes, that seems very much like a bug to me. Thanks for reporting it and suggesting a fix for it. I'll probably have time to make a fix and release a new version over the weekend.

**Comment by patrikerdes** [comment]
This is now released in 0.2.10
