### ISSUE TITLE
Gradle Kotlin DSL

### ISSUE THREAD

**Issue by AOrobator** [patrikerdes/gradle-use-latest-versions-plugin#29]
Are there any plans to support the kotlin gradle dsl?

**Comment by patrikerdes** [comment]
It has been supported since version 0.2.1. Is there anything in particular that is not working for you?

**Comment by AOrobator** [comment]
No, was just curious. Closing this out

**Comment by AOrobator** [comment]
I'd recommend adding that it supports the Kotlin Gradle DSL on the readme ;)

**Comment by patrikerdes** [comment]
There is already a section called "Usage for Gradle Kotlin DSL" https://github.com/patrikerdes/gradle-use-latest-versions-plugin#usage-for-gradle-kotlin-dsl
