### ISSUE TITLE
Failing tests: ben-manes plugin not found

### ISSUE THREAD

**Issue by joschjava** [patrikerdes/gradle-use-latest-versions-plugin#34]
I improved the plugin and wanted to run the Unit Tests. However, for most of the tests the following message showed up. Can you help me with this?

Unexpected build execution failure in C:\Users\USERNAME\AppData\Local\Temp\junit2740443000582118919 with arguments [useLatestVersions]

Output:

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Users\USERNAME\AppData\Local\Temp\junit2740443000582118919\build.gradle' line: 4

* What went wrong:
Plugin [id: 'com.github.ben-manes.versions', version: '0.21.0'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Gradle TestKit (classpath: PROJECTPATH\build\classes\java\main;PROJECTPATH\build\classes\groovy\main;PROJECTPATH\build\resources\main)
- Plugin Repositories (could not resolve plugin artifact 'com.github.ben-manes.versions:com.github.ben-manes.versions.gradle.plugin:0.21.0')
  Searched in the following repositories:
    Gradle Central Plugin Repository

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s

**Comment by patrikerdes** [comment]
Which command did you execute when you got this error? Were you using the gradle wrapper?

**Comment by patrikerdes** [comment]
There were other issues causing the unit tests to fail, which I have now fixed. Now all unit tests ran successfully for me locally (on windows) and on Travis-CI (on linux).
Could you try running the tests with the gradle wrapper, and see if that works? (`./gradlew build`)

**Comment by patrikerdes** [comment]
This seems to be a problem with the test runner and not with this project, so I'm closing this for now. Please reopen if you are still having issues when running `./graldew build`.
