### ISSUE TITLE
Task :internalRootAggregate FAILED - java.lang.ClassCastException

### ISSUE THREAD

**Issue by xeruf** [patrikerdes/gradle-use-latest-versions-plugin#46]
I recently had an error trying to use use-latest-versions in a multi-module build:
```sh
> Task :internalRootAggregate FAILED

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':sdk:useLatestVersions'.
> java.lang.ClassCastException: class org.apache.xerces.parsers.XIncludeAwareParserConfiguration cannot be cast to class org.apache.xerces.xni.parser.XMLParserConfiguration (org.apache.xerces.parsers.XIncludeAwareParserConfiguration is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @456aaa6f; org.apache.xerces.xni.parser.XMLParserConfiguration is in unnamed module of loader org.gradle.internal.classloader.VisitableURLClassLoader @36faac92)
```
Using OpenJDK 14 on this commit: https://github.com/CAU-Kiel-Tech-Inf/backend/tree/use-latest-versions-bug
I simply ran `./gradlew useLatestVersions`, and it failed for the subprojects. `dependencyUpdates` worked. Logs:

[dependencyUpdates.txt](https://github.com/patrikerdes/gradle-use-latest-versions-plugin/files/5354132/dependencyUpdates.txt)
[useLatestVersions.txt](https://github.com/patrikerdes/gradle-use-latest-versions-plugin/files/5354133/useLatestVersions.txt)

Interestingly the issue vanished when I updated some dependencies: https://github.com/CAU-Kiel-Tech-Inf/backend/commit/02e3fb143ea9ab1363c5db203b9590628a32a834

**Comment by gabriel-TheCode** [comment]
Same problem. Any solution ?

**Comment by gabriel-TheCode** [comment]
Thanks; It works fine.
```
buildscript {
  dependencies {
    configurations.classpath.exclude group: 'xerces', module: 'xercesImpl'
  }
}
```

**Comment by patrikerdes** [comment]
Closing since a workaround exists.
