### ISSUE TITLE
Erroneous "The variable ... is assigned more than once" message if variable has another as a suffix

### ISSUE THREAD

**Issue by xenomachina** [patrikerdes/gradle-use-latest-versions-plugin#51]
## To reproduce:

1. Create a new project with the following `build.gradle` and `gradle.properties` files:

   ### build.gradle

   ``` gradle
   buildscript {
       repositories {
           mavenCentral()
       }

       dependencies {
           classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
       }
   }

   plugins {
     id("se.patrikerdes.use-latest-versions") version "0.2.16"
     id("com.github.ben-manes.versions") version "0.38.0"
   }

   apply plugin: 'kotlin'

   dependencies {
       implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
   }
   ```

   ### gradle.properties

   ``` properties
   dotenv_kotlin_version = 6.2.2
   kotlin_version = 1.4.30
   ```

2. Install gradle wrapper 7.0:

   ``` bash
   gradle wrapper --gradle-version 7.0
   ```

3. Execute `./gradlew useLatestVersions`

## Expected behavior

It should update `kotlin_version` (to 1.5.0, at the time I write this).

## Actual behavior

It complains...

> A problem was detected: the variable kotlin_version is assigned more than once and won't be changed.

...and does *not* update `kotlin_version`.

## Work around

Ensure that no two version variables are a suffix of each other. In this case, `kotlin_version` is a suffix of `dotenv_kotlin_version`, so one or the other needs to be renamed.

**Comment by patrikerdes** [comment]
Yes, I think I know why this would happen; a bad regex. 😝

This should be a pretty straight forward fix for anyone interested in helping out: write a failing test case according to the bug report, find the offending regex and fix it so the new test is passing, while making sure all existing tests are still passing.

**Comment by xenomachina** [comment]
Ok, I've sent a PR.
