### ISSUE TITLE
kotlin("plugin.spring") isn't updated

### ISSUE THREAD

**Issue by JorgenRingen** [patrikerdes/gradle-use-latest-versions-plugin#57]
Added a test demonstrating the behavior: https://github.com/JorgenRingen/gradle-use-latest-versions-plugin/commit/837a8001d61c2da2367cca1ecd3623fd52988902

As you can see, `kotlin("jvm")` is updated, but `kotlin("plugin.spring")` is not updated.

However, when I declare the plugin like this it works: `id("org.jetbrains.kotlin.plugin.spring")`

NB: The test was a little bit broken as well as assertions didn't fail when they ran inside lambda. Added assert keyword to make the test fail if an assertion failed.

**Comment by andeki92** [comment]
This would be incredibly helpful! 🙌

**Comment by patrikerdes** [comment]
Available in 0.2.18
