### ISSUE TITLE
Restricting to certain group IDs

### ISSUE THREAD

**Issue by sonOfRa** [patrikerdes/gradle-use-latest-versions-plugin#6]
Is there a way to make the plugin only touch versions of certain group IDs? Essentially, we depend on SNAPSHOT versions of our own libraries between releases, move to non-snapshot on release, and to next-snapshot after release. I'd like to automate this process, and this plugin looks very useful.

However, I want to only touch the versions of dependencies that are under the group ID "com.example", but not any of the other dependencies (like build tooling, etc). Is this possible?

**Comment by sonOfRa** [comment]
Figured out how to do it, you can configure the underlying plugin like this:

```gradle
dependencyUpdates.resolutionStrategy {
    componentSelection { rules ->
        rules.all { ComponentSelection selection ->
            if (selection.candidate.group != "com.example") {
                selection.reject('Only update com.example dependencies!')
            }
        }
    }
}
```

**Comment by patrikerdes** [comment]
Thanks for posting the solution 👍
