### ISSUE TITLE
Feature request: Update version variables in gradle.properties file

### ISSUE THREAD

**Issue by usr42** [patrikerdes/gradle-use-latest-versions-plugin#7]
I have some gradle projects where the version of dependencies is defined in the `gradle.properties` file in the project root directory. These versions are detected correctly, but are not automatically updated.

This would be a really helpful feature. 

Thank you for the great work already done. 

Cheers, 
usr42

**Comment by patrikerdes** [comment]
Fixed in 0.2.4
