### ISSUE TITLE
Support for string interpolation with curly braces ${}

### ISSUE THREAD

**Issue by usr42** [patrikerdes/gradle-use-latest-versions-plugin#8]
First, thanks for the super-fast implementation of https://github.com/patrikerdes/gradle-use-latest-versions-plugin/issues/7

Now to my new request:
Using the dollar-only notation `$versionVariable` works. 
But Groovy and Kotlin (and so gradle DSL) also supports the dollar with curly braces notation: `${versionVariable}`
If I use this notation the version is not automatically updated.

Example to reproduce:
```
dependencies {
    ext {
        junitJupiterVersion='5.3.0-RC1'
    }

    testCompile "org.junit.jupiter:junit-jupiter-api:${junitJupiterVersion}"
    testRuntime "org.junit.jupiter:junit-jupiter-engine:${junitJupiterVersion}"
}
```

The following is successful:
```
dependencies {
    ext {
        junitJupiterVersion='5.3.0-RC1'
    }

    testCompile "org.junit.jupiter:junit-jupiter-api:$junitJupiterVersion"
    testRuntime "org.junit.jupiter:junit-jupiter-engine:$junitJupiterVersion"
}
```

It would be nice if also the curly braces (`${}`) notation would work.

Thanks and cheers,
usr42 / Balthasar

**Comment by patrikerdes** [comment]
Thanks for reporting this 👍 
Fixed in 0.2.5
